---
abstract: ~
author:
  - 'Kevin Falcone <falcone@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gplv2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-MintingProfile-RTx
no_index:
  directory:
    - inc
    - profiles
requires:
  Dist::Zilla: 0
  Module::Install::RTx: 0
  Module::Install::ReadmeFromPod: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.09
